整理config文件,增加小米Mini 同步gorden5566的汉化字典(42bab8a) 增加clean_tree_simple脚本

diff --git a/trunk/build_firmware_modify b/trunk/build_firmware_modify
--- a/trunk/build_firmware_modify
+++ b/trunk/build_firmware_modify
@@ -1,5 +1,12 @@
 #!/bin/sh
-cp -f configs/templates/PSG1218.config .config
+
+if [ ! -f configs/templates/$1.config ] ; then
+	echo "configs/templates/$1.config not found "
+	exit 1
+fi
+
+cp -f configs/templates/$1.config .config
+
 ROOTDIR=`pwd`
 export ROOTDIR=$ROOTDIR
 
@@ -487,4 +494,3 @@ echo --------------------------MAKE-DEP--------------------------------
 make dep
 echo --------------------------MAKE-ALL--------------------------------
 make
-#invaild items(DISABLED):USB,NFSC,NFSD,CIFS,SMBD,USB AUDIO,USB UVC,OPENVPN
diff --git a/trunk/build_firmware_nohup b/trunk/build_firmware_nohup
--- a/trunk/build_firmware_nohup
+++ b/trunk/build_firmware_nohup
@@ -1,7 +1,12 @@
 #!/bin/sh
+if [ ! -f configs/templates/$1.config ] ; then
+	echo "configs/templates/$1.config not found "
+	exit 1
+fi
+
 rm -f nohup.out
 touch nohup.out
-nohup ./build_firmware_k2_nousb &
+nohup ./build_firmware_modify $1 &
 
 tail_last=test
 while true ;do
@@ -19,3 +24,4 @@ tail_last=$(tail -1 nohup.out)
 tail -4 nohup.out
 sleep 30
 done
+
