update README.md

diff --git a/trunk/build_firmware_modify b/trunk/build_firmware_modify
--- a/trunk/build_firmware_modify
+++ b/trunk/build_firmware_modify
@@ -1,11 +1,13 @@
 #!/bin/bash
 
 if [ -z "$1" ] || [ "$EUID" != 0 ]; then
-	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1
+	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/')"
+	echo "For Windows Subsystem for Linux(WSL), use 'fakeroot-tcp' instead of 'fakeroot', or run with sudo"
+	exit 1
 fi
 
 if [ ! -f configs/templates/$1.config ] ; then
-	echo "configs/templates/$1.config not found "
+	echo "configs/templates/$1.config not found!"
 	exit 1
 fi
 
