update scripts

diff --git a/trunk/user/napt66/scripts/start_napt66 b/trunk/user/napt66/scripts/start_napt66
--- a/trunk/user/napt66/scripts/start_napt66
+++ b/trunk/user/napt66/scripts/start_napt66
@@ -8,7 +8,7 @@ if [ -f "$kmod_napt66" ]; then
 		mtd_storage.sh save > /dev/null 2>&1
 		restart_firewall
 	fi
-	insmod $kmod_napt66 wan_if=$(nvram get wan_ifname)
+	insmod $kmod_napt66 wan_if=$(nvram get wan_ifname) || echo "napt66 load fail!"
 else
 	echo "$kmod_napt66 not found"
 fi
